name: Build Android

on: [push, pull_request]

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Setup OpenGL on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install xorg-dev
          sudo apt-get install freeglut3-dev
          sudo apt-get install libopengl0

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          path: main

      - name: Install dependencies
        run: yarn --frozen-lockfile
        working-directory: ./main

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Checkout Keys
        uses: actions/checkout@v2
        with:
          repository: highduck/keys
          token: ${{ secrets.GH_TOKEN }}
          path: keys

      - name: Build Android
        run: yarn run build:android
        working-directory: ./main
