name: Build Android

on: [push, pull_request]

jobs:
  build-android:
    # skip
    if: false

    name: Build Android
    runs-on: ubuntu-latest
    steps:
      # checkout repositories
      - name: Checkout Engine
        uses: actions/checkout@v2
        with:
          repository: highduck/ekx
          token: ${{ secrets.GH_TOKEN }}
          path: ekx

      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          path: main

      # setup native build tools
      - name: Setup OpenGL on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install xorg-dev
          sudo apt-get install freeglut3-dev
          sudo apt-get install libopengl0

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      # build local dependencies
      - name: Prepare @ekx/cli
        run: yarn --frozen-lockfile && yarn run build && yarn link -g
        working-directory: ./ekx/cli

      - name: Prepare @ekx/ekx
        run: yarn --frozen-lockfile
        working-directory: ./ekx

      - name: Install dependencies
        run: yarn --frozen-lockfile
        working-directory: ./main

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Checkout Keys
        uses: actions/checkout@v2
        with:
          repository: highduck/keys
          token: ${{ secrets.GH_TOKEN }}
          path: keys

      - name: Build Android
        run: yarn run build:android
        working-directory: ./main
