name: Build

on: [push, pull_request]

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      # strange but we cannot use ninja from NDK?
      - name: Setup Ninja
        uses: eliasku/gha-setup-ninja@master

      # See b/206099937. Hack needed to make ninja visible to cmake during NDK builds
      - name: Link Ninja binary
        run: ln -s "${GITHUB_WORKSPACE}/ninja-build/ninja" "/usr/local/bin/ninja"

      - name: Install WebP (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install webp

      - name: Install WebP (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew list webp || brew install webp

#      - name: Set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'zulu'
#          java-version: '11'
#          java-package: jdk # optional (jdk or jre) - defaults to jdk

#      - name: Setup Android SDK
#        uses: android-actions/setup-android@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          path: main

      - name: Install dependencies
        run: yarn --frozen-lockfile
        working-directory: ./main

      - name: Checkout Keys
        uses: actions/checkout@v3
        with:
          repository: highduck/keys
          token: ${{ secrets.GH_TOKEN }}
          path: keys

      - name: Build Android
        run: yarn run build:android
        working-directory: ./main

  build-web:
    name: Build Web
    runs-on: ubuntu-latest
    env:
      EM_VERSION: 3.1.8
      EM_CACHE_FOLDER: 'emsdk-cache'
    steps:
      # setup native build tools
      - name: Setup system cache
        id: cache-system-libraries
        uses: actions/cache@v2
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}-${{ runner.os }}

      - name: Setup Ninja
        uses: eliasku/gha-setup-ninja@master

      - name: Install WebP (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install webp

      - name: Install WebP (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew list webp || brew install webp

      - name: Install CCache
        uses: eliasku/install-ccache-action@master

      - name: Setup CCache
        uses: eliasku/ccache-action@main
        with:
          key: ${{ runner.os }}

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          path: main

      - name: Install dependencies
        run: yarn --frozen-lockfile
        working-directory: ./main

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      - name: Keys
        uses: actions/checkout@v3
        with:
          repository: highduck/keys
          token: ${{ secrets.GH_TOKEN }}
          path: keys

      - name: Build and Release Web
        run: yarn release-patch-web
        working-directory: ./main
